pipeline {
    agent any

    stages {

        stage('Deploy Dev Stage on docker') {
            steps {
                dir('setup/tomcat') {
                    sh 'docker-compose down'
                    sh 'docker-compose up -d'
                }
            }
        }
    }
    post {
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
