apiVersion: v1
kind: Service
metadata:
  name: springboot-nodeport
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31002
  selector:
    app: springboot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: {{ .Values.images.spring_boot_app }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: PSQL_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: spring-boot-config-map
              key: PSQL_DB_HOST
        - name: PSQL_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: spring-boot-config-map
              key: PSQL_DB_PORT
        - name: PSQL_DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-key
              key: PSQL_DB_USER
        - name: PSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-key
              key: PSQL_DB_PASSWORD
        - name: PSQL_DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-key
              key: PSQL_DB_DATABASE
