version: "3.8"

services:
  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      db:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data1:/opt/sonarqube/data
      - sonarqube_extensions1:/opt/sonarqube/extensions
      - sonarqube_logs1:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - sonarqube
  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: postgresqlsonar
    container_name: postgresqlsonar
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresqls1:/var/lib/postgresql
      - postgresql_datas1:/var/lib/postgresql/data
    networks:
      - sonarqube

volumes:
  sonarqube_data1:
  sonarqube_extensions1:
  sonarqube_logs1:
  postgresqls1:
  postgresql_datas1:


networks:
  sonarqube:
    name: sonarqube
    driver: bridge