apiVersion: v1
kind: Secret
metadata:
  name: postgres-key
type: Opaque
data:
  PSQL_DB_USER: {{ .Values.postgres.username | b64enc }}
  PSQL_DB_PASSWORD: {{ .Values.postgres.password | b64enc }}
  PSQL_DB_DATABASE: {{ .Values.postgres.db_name | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.admin_password | b64enc }}